package com.hermes.android.ui.theme

import androidx.compose.ui.graphics.Color

// Hermes2 Material 3 palette — deep agent console + cyan/violet accents.
// Tuned for Android OLED dark mode while keeping a readable light mode.

// Light theme
val md_light_primary = Color(0xFF5B4BDB)
val md_light_onPrimary = Color(0xFFFFFFFF)
val md_light_primaryContainer = Color(0xFFE5DEFF)
val md_light_onPrimaryContainer = Color(0xFF17005C)
val md_light_secondary = Color(0xFF006A78)
val md_light_onSecondary = Color(0xFFFFFFFF)
val md_light_secondaryContainer = Color(0xFFA8EEFF)
val md_light_onSecondaryContainer = Color(0xFF001F26)
val md_light_tertiary = Color(0xFF256A4F)
val md_light_onTertiary = Color(0xFFFFFFFF)
val md_light_tertiaryContainer = Color(0xFFA9F2CF)
val md_light_onTertiaryContainer = Color(0xFF002115)
val md_light_error = Color(0xFFBA1A1A)
val md_light_onError = Color(0xFFFFFFFF)
val md_light_errorContainer = Color(0xFFFFDAD6)
val md_light_onErrorContainer = Color(0xFF410002)
val md_light_background = Color(0xFFF8FAFF)
val md_light_onBackground = Color(0xFF171A23)
val md_light_surface = Color(0xFFFFFFFF)
val md_light_onSurface = Color(0xFF171A23)
val md_light_surfaceVariant = Color(0xFFE2E5F2)
val md_light_onSurfaceVariant = Color(0xFF444754)
val md_light_outline = Color(0xFF747785)
val md_light_outlineVariant = Color(0xFFC4C6D4)

// Dark theme
val md_dark_primary = Color(0xFF9B8CFF)
val md_dark_onPrimary = Color(0xFF24008A)
val md_dark_primaryContainer = Color(0xFF3F2CB5)
val md_dark_onPrimaryContainer = Color(0xFFE8DDFF)
val md_dark_secondary = Color(0xFF67D9F2)
val md_dark_onSecondary = Color(0xFF003640)
val md_dark_secondaryContainer = Color(0xFF004E5C)
val md_dark_onSecondaryContainer = Color(0xFFB6EBFF)
val md_dark_tertiary = Color(0xFF7EDDB3)
val md_dark_onTertiary = Color(0xFF003823)
val md_dark_tertiaryContainer = Color(0xFF005137)
val md_dark_onTertiaryContainer = Color(0xFF9AF8CD)
val md_dark_error = Color(0xFFFFB4AB)
val md_dark_onError = Color(0xFF690005)
val md_dark_errorContainer = Color(0xFF93000A)
val md_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_dark_background = Color(0xFF080D16)
val md_dark_onBackground = Color(0xFFE4E8F4)
val md_dark_surface = Color(0xFF0D1420)
val md_dark_onSurface = Color(0xFFE4E8F4)
val md_dark_surfaceVariant = Color(0xFF202938)
val md_dark_onSurfaceVariant = Color(0xFFC3CAD8)
val md_dark_outline = Color(0xFF8D95A6)
val md_dark_outlineVariant = Color(0xFF3D4658)
