package com.hermes.android.ui.theme

import androidx.compose.ui.graphics.Color

// Light theme — inspired by Hermes TUI accent colors
val md_light_primary = Color(0xFF1B6B5C)
val md_light_onPrimary = Color(0xFFFFFFFF)
val md_light_primaryContainer = Color(0xFF9CF0DE)
val md_light_onPrimaryContainer = Color(0xFF00201A)
val md_light_secondary = Color(0xFF4A635C)
val md_light_onSecondary = Color(0xFFFFFFFF)
val md_light_secondaryContainer = Color(0xFFCDE8DE)
val md_light_onSecondaryContainer = Color(0xFF06201B)
val md_light_tertiary = Color(0xFF446279)
val md_light_onTertiary = Color(0xFFFFFFFF)
val md_light_tertiaryContainer = Color(0xFFC9E6FF)
val md_light_onTertiaryContainer = Color(0xFF001E30)
val md_light_error = Color(0xFFBA1A1A)
val md_light_onError = Color(0xFFFFFFFF)
val md_light_errorContainer = Color(0xFFFFDAD6)
val md_light_onErrorContainer = Color(0xFF410002)
val md_light_background = Color(0xFFFAFDFB)
val md_light_onBackground = Color(0xFF191C1B)
val md_light_surface = Color(0xFFFAFDFB)
val md_light_onSurface = Color(0xFF191C1B)
val md_light_surfaceVariant = Color(0xFFDBE5E0)
val md_light_onSurfaceVariant = Color(0xFF3F4945)
val md_light_outline = Color(0xFF6F7975)
val md_light_outlineVariant = Color(0xFFBFC9C4)

// Dark theme
val md_dark_primary = Color(0xFF80D4C2)
val md_dark_onPrimary = Color(0xFF00382E)
val md_dark_primaryContainer = Color(0xFF005144)
val md_dark_onPrimaryContainer = Color(0xFF9CF0DE)
val md_dark_secondary = Color(0xFFB1CCC2)
val md_dark_onSecondary = Color(0xFF1C352E)
val md_dark_secondaryContainer = Color(0xFF334B44)
val md_dark_onSecondaryContainer = Color(0xFFCDE8DE)
val md_dark_tertiary = Color(0xFFAACBE5)
val md_dark_onTertiary = Color(0xFF113348)
val md_dark_tertiaryContainer = Color(0xFF2A4A60)
val md_dark_onTertiaryContainer = Color(0xFFC9E6FF)
val md_dark_error = Color(0xFFFFB4AB)
val md_dark_onError = Color(0xFF690005)
val md_dark_errorContainer = Color(0xFF93000A)
val md_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_dark_background = Color(0xFF191C1B)
val md_dark_onBackground = Color(0xFFE1E3E0)
val md_dark_surface = Color(0xFF191C1B)
val md_dark_onSurface = Color(0xFFE1E3E0)
val md_dark_surfaceVariant = Color(0xFF3F4945)
val md_dark_onSurfaceVariant = Color(0xFFBFC9C4)
val md_dark_outline = Color(0xFF899390)
val md_dark_outlineVariant = Color(0xFF3F4945)
