package com.hermes.android.runtime.termux

import android.content.Context
import dagger.hilt.android.qualifiers.ApplicationContext
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Generates the bash install command for Termux using install.sh's native
 * --stage and --json API (Fix S2F02, S2F04).
 *
 * install.sh supports:
 *   --manifest  → outputs JSON stage list
 *   --stage NAME → runs one stage
 *   --json       → outputs JSON result for the stage
 *
 * The generated script:
 * 1. Downloads install.sh
 * 2. Runs --manifest to get the stage list
 * 3. Runs each stage with --stage NAME --json
 * 4. Reports progress via am broadcast after each stage
 * 5. Verifies hermes --version and hermes doctor (Fix S2F05, S2F06)
 * 6. Reports Python version (Fix S2F01)
 *
 * Reference: ADR-007, scripts/install.sh:124-128, 271, 282-292
 */
@Singleton
class TermuxInstaller @Inject constructor(
    @ApplicationContext private val context: Context,
) {

    enum class BroadcastAction(val action: String) {
        PROGRESS("com.hermes.android.INSTALL_PROGRESS"),
        COMPLETE("com.hermes.android.INSTALL_COMPLETE"),
        ERROR("com.hermes.android.INSTALL_ERROR"),
    }

    /**
     * The pure bash script body that performs the Hermes install inside Termux.
     *
     * This is the canonical install script. It is sent to Termux via
     * [TermuxCommandExecutor.executeBackgroundScript] — NOT via copy/paste.
     * Kept as a separate method so the script can be unit-tested and reused
     * by both the automated path and (as a fallback) the legacy copy/paste
     * instructions screen.
     */
    fun generateInstallScript(): String {
        val receiver = context.packageName
        return buildString {
            appendLine("# Hermes Agent — Android install script")
            appendLine("# Generated by Hermes2 app. Executed automatically via RUN_COMMAND.")
            appendLine("# Uses install.sh native --stage --json API")
            appendLine("set -e")
            appendLine()
            appendLine("RECEIVER=\"$receiver\"")
            appendLine("PROGRESS_ACTION=\"${BroadcastAction.PROGRESS.action}\"")
            appendLine("COMPLETE_ACTION=\"${BroadcastAction.COMPLETE.action}\"")
            appendLine("ERROR_ACTION=\"${BroadcastAction.ERROR.action}\"")
            appendLine("INSTALL_URL=\"https://hermes-agent.nousresearch.com/install.sh\"")
            appendLine()
            appendLine("report_progress() {")
            appendLine("    local stage=\"\$1\" message=\"\$2\" percent=\"\$3\"")
            appendLine("    am broadcast -p \"\$RECEIVER\" -a \"\$PROGRESS_ACTION\" \\")
            appendLine("        --es stage \"\$stage\" \\")
            appendLine("        --es message \"\$message\" \\")
            appendLine("        --ei percent \"\$percent\" >/dev/null 2>&1 || true")
            appendLine("}")
            appendLine()
            appendLine("report_complete() {")
            appendLine("    am broadcast -p \"\$RECEIVER\" -a \"\$COMPLETE_ACTION\" >/dev/null 2>&1 || true")
            appendLine("}")
            appendLine()
            appendLine("report_error() {")
            appendLine("    local message=\"\$1\"")
            appendLine("    am broadcast -p \"\$RECEIVER\" -a \"\$ERROR_ACTION\" --es message \"\$message\" >/dev/null 2>&1 || true")
            appendLine("}")
            appendLine()
            appendLine("trap 'report_error \"Install failed at stage: \$STAGE\"' ERR")
            appendLine()
            appendLine("# Download install.sh")
            appendLine("STAGE=\"repository\"")
            appendLine("report_progress \"\$STAGE\" \"Downloading Hermes Agent installer...\" 5")
            appendLine("curl -fsSL \"\$INSTALL_URL\" -o /tmp/hermes_install.sh")
            appendLine("chmod +x /tmp/hermes_install.sh")
            appendLine()
            appendLine("# Get stage manifest (Fix S2F02: use --manifest)")
            appendLine("MANIFEST=\$(bash /tmp/hermes_install.sh --manifest 2>/dev/null)")
            appendLine("if [ -z \"\$MANIFEST\" ]; then")
            appendLine("    # Fallback: run install.sh directly if manifest fails")
            appendLine("    STAGE=\"prerequisites\"")
            appendLine("    report_progress \"\$STAGE\" \"Running install.sh...\" 10")
            appendLine("    bash /tmp/hermes_install.sh")
            appendLine("else")
            appendLine("    # Parse stages and run each with --stage --json (Fix S2F02)")
            appendLine("    STAGE_COUNT=\$(echo \"\$MANIFEST\" | python3 -c \"import sys,json; print(len(json.loads(sys.stdin.read())['stages']))\" 2>/dev/null || echo 10)")
            appendLine("    CURRENT=0")
            appendLine("    for STAGE in prerequisites repository venv python-deps node-deps path config complete; do")
            appendLine("        CURRENT=\$((CURRENT + 1))")
            appendLine("        PERCENT=\$((CURRENT * 90 / STAGE_COUNT))")
            appendLine("        report_progress \"\$STAGE\" \"Running stage: \$STAGE\" \$PERCENT")
            appendLine("        # Run stage with --json output (Fix S2F02)")
            appendLine("        STAGE_RESULT=\$(bash /tmp/hermes_install.sh --stage \"\$STAGE\" --json 2>&1) || {")
            appendLine("            # setup and gateway need user input, skip on non-interactive")
            appendLine("            if [ \"\$STAGE\" = \"setup\" ] || [ \"\$STAGE\" = \"gateway\" ]; then")
            appendLine("                report_progress \"\$STAGE\" \"Skipped (needs user input)\" \$PERCENT")
            appendLine("                continue")
            appendLine("            fi")
            appendLine("            report_error \"Stage \$STAGE failed: \$STAGE_RESULT\"")
            appendLine("            exit 1")
            appendLine("        }")
            appendLine("    done")
            appendLine("fi")
            appendLine()
            appendLine("# Verify: hermes --version (Fix S2F05)")
            appendLine("STAGE=\"verify_version\"")
            appendLine("report_progress \"\$STAGE\" \"Checking hermes --version...\" 92")
            appendLine("if ! command -v hermes >/dev/null 2>&1; then")
            appendLine("    report_error \"hermes command not found on PATH\"")
            appendLine("    exit 1")
            appendLine("fi")
            appendLine("HERMES_VERSION=\$(hermes --version 2>&1 || echo \"unknown\")")
            appendLine("am broadcast -p \"\$RECEIVER\" -a \"\$PROGRESS_ACTION\" \\")
            appendLine("    --es stage \"verify_version\" \\")
            appendLine("    --es message \"Hermes version: \$HERMES_VERSION\" \\")
            appendLine("    --ei percent 94 >/dev/null 2>&1 || true")
            appendLine()
            appendLine("# Verify: hermes doctor (Fix S2F06)")
            appendLine("STAGE=\"verify_doctor\"")
            appendLine("report_progress \"\$STAGE\" \"Running hermes doctor...\" 96")
            appendLine("DOCTOR_OUTPUT=\$(hermes doctor 2>&1 || echo \"doctor failed\")")
            appendLine("am broadcast -p \"\$RECEIVER\" -a \"\$PROGRESS_ACTION\" \\")
            appendLine("    --es stage \"verify_doctor\" \\")
            appendLine("    --es message \"Doctor: \$DOCTOR_OUTPUT\" \\")
            appendLine("    --ei percent 98 >/dev/null 2>&1 || true")
            appendLine()
            appendLine("# Detect Python version (Fix S2F01)")
            appendLine("PYTHON_VERSION=\$(python3 --version 2>&1 || echo \"unknown\")")
            appendLine("am broadcast -p \"\$RECEIVER\" -a \"\$PROGRESS_ACTION\" \\")
            appendLine("    --es stage \"python_version\" \\")
            appendLine("    --es message \"Python: \$PYTHON_VERSION\" \\")
            appendLine("    --ei percent 99 >/dev/null 2>&1 || true")
            appendLine()
            appendLine("STAGE=\"complete\"")
            appendLine("report_progress \"\$STAGE\" \"Installation complete! Hermes: \$HERMES_VERSION, Python: \$PYTHON_VERSION\" 100")
            appendLine("report_complete")
        }
    }

    /**
     * Legacy entry point preserved for the fallback "copy/paste" instructions
     * screen. The automated path uses [generateInstallScript] instead.
     */
    fun generateInstallCommand(): String = generateInstallScript()

    fun getScriptFilePath(): java.io.File? = null
}
