package com.hermes.android.runtime.termux

import android.content.BroadcastReceiver
import android.content.Context
import android.content.Intent
import com.hermes.android.runtime.InstallProgress
import kotlinx.coroutines.flow.MutableStateFlow
import timber.log.Timber

/**
 * Receives progress broadcasts from the install script running in Termux.
 *
 * The install script (generated by [TermuxInstaller]) sends `am broadcast`
 * intents with progress/complete/error actions. This receiver picks them up
 * and updates the shared state flows.
 *
 * Registered dynamically (not in manifest) because the receiver should only
 * be active during installation.
 *
 * Note: NOT using @AndroidEntryPoint because the receiver is registered
 * dynamically via Context.registerReceiver(), which creates the instance
 * via no-arg constructor — Hilt cannot inject into dynamically-registered
 * receivers. Instead, the shared StateFlows are accessed via a companion
 * object that the TermuxBridge sets before registering.
 *
 * Reference: ADR-007 (reuse install.sh — migration only)
 */
class TermuxInstallProgressReceiver : BroadcastReceiver() {

    override fun onReceive(context: Context, intent: Intent) {
        when (intent.action) {
            TermuxInstaller.BroadcastAction.PROGRESS.action -> {
                val stage = intent.getStringExtra("stage") ?: "unknown"
                val message = intent.getStringExtra("message") ?: ""
                val percent = intent.getIntExtra("percent", -1).takeIf { it >= 0 }
                val progress = InstallProgress(
                    stage = stage,
                    message = message,
                    percent = percent,
                    timestamp = System.currentTimeMillis(),
                )
                Timber.i("[Runtime] Install progress: $progress")
                sharedProgressFlow?.value = progress
            }

            TermuxInstaller.BroadcastAction.COMPLETE.action -> {
                Timber.i("[Runtime] Install complete broadcast received")
                sharedCompletionFlow?.value = InstallCompletion.Completed
            }

            TermuxInstaller.BroadcastAction.ERROR.action -> {
                val message = intent.getStringExtra("message") ?: "Unknown error"
                Timber.e("[Runtime] Install error broadcast received: $message")
                sharedCompletionFlow?.value = InstallCompletion.Failed(message)
            }
        }
    }

    /** Sealed type for install completion status. */
    sealed class InstallCompletion {
        object Pending : InstallCompletion()
        object Completed : InstallCompletion()
        data class Failed(val message: String) : InstallCompletion()
    }

    companion object {
        /**
         * Shared flows — set by [TermuxBridge] before registering this receiver.
         * This avoids Hilt injection issues with dynamically-registered receivers.
         */
        @Volatile
        var sharedProgressFlow: MutableStateFlow<InstallProgress?>? = null

        @Volatile
        var sharedCompletionFlow: MutableStateFlow<InstallCompletion>? = null
    }
}
