package com.hermes.android.runtime.termux

import android.content.Context
import dagger.hilt.android.qualifiers.ApplicationContext
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Generates the bash install command for Termux using install.sh's native
 * --stage and --json API (Fix S2F02, S2F04).
 *
 * install.sh supports:
 *   --manifest  → outputs JSON stage list
 *   --stage NAME → runs one stage
 *   --json       → outputs JSON result for the stage
 *
 * The generated script:
 * 1. Downloads install.sh
 * 2. Runs --manifest to get the stage list
 * 3. Runs each stage with --stage NAME --json
 * 4. Reports progress via am broadcast after each stage
 * 5. Verifies hermes --version and hermes doctor (Fix S2F05, S2F06)
 * 6. Reports Python version (Fix S2F01)
 *
 * ## Robustness (survives app crash / screen off / network drop)
 * The script runs inside Termux, independent of this app's process, and is
 * hardened so a flaky phone can't corrupt the install:
 * - **Persistent state** — every progress/error/complete update is also
 *   written atomically to `~/.hermes/install.state`. If the app dies, the
 *   state survives; [generateStateResyncScript] re-broadcasts it on demand.
 * - **Wake lock** — `termux-wake-lock` (when available) stops Android from
 *   freezing Termux mid-compile with the screen off.
 * - **Single-instance lock** — a PID file prevents two installers racing.
 * - **Stage checkpoints** — completed stages are recorded in
 *   `~/.hermes/.install-done-stages`; a re-run **resumes**, skipping them.
 * - **Retries** — each stage gets 3 attempts with a network-wait between
 *   them, so a transient outage doesn't kill a 15-minute install.
 * - **Interrupt detection** — an EXIT trap marks the state `failed` if the
 *   script dies while still `running`, so the app can offer Resume.
 *
 * Reference: ADR-007, scripts/install.sh:124-128, 271, 282-292
 */
@Singleton
class TermuxInstaller @Inject constructor(
    @ApplicationContext private val context: Context,
) {

    enum class BroadcastAction(val action: String) {
        PROGRESS("com.hermes.android.INSTALL_PROGRESS"),
        COMPLETE("com.hermes.android.INSTALL_COMPLETE"),
        ERROR("com.hermes.android.INSTALL_ERROR"),
    }

    /**
     * The pure bash script body that performs the Hermes install inside Termux.
     *
     * This is the canonical install script. It is sent to Termux via
     * [TermuxCommandExecutor.executeBackgroundScript] — NOT via copy/paste.
     * Kept as a separate method so the script can be unit-tested and reused
     * by both the automated path and (as a fallback) the legacy copy/paste
     * instructions screen.
     */
    fun generateInstallScript(): String {
        val receiver = context.packageName
        return buildString {
            appendLine("# Hermes Agent — Android install script")
            appendLine("# Generated by Hermes2 app. Executed automatically via RUN_COMMAND.")
            appendLine("# Uses install.sh native --stage --json API")
            appendLine("set -e")
            appendLine("set -o pipefail")
            appendLine()
            appendLine("RECEIVER=\"$receiver\"")
            appendLine("PROGRESS_ACTION=\"${BroadcastAction.PROGRESS.action}\"")
            appendLine("COMPLETE_ACTION=\"${BroadcastAction.COMPLETE.action}\"")
            appendLine("ERROR_ACTION=\"${BroadcastAction.ERROR.action}\"")
            appendLine("INSTALL_URL=\"https://hermes-agent.nousresearch.com/install.sh\"")
            appendLine("REPO_DIR=\"\$HOME/.hermes/hermes-agent\"")
            appendLine("STATE_FILE=\"\$HOME/.hermes/install.state\"")
            appendLine("DONE_FILE=\"\$HOME/.hermes/.install-done-stages\"")
            appendLine("LOCK_FILE=\"\$HOME/.hermes/.install.pid\"")
            appendLine("mkdir -p \"\$HOME/.hermes/logs\"")
            appendLine()
            appendLine("# Persistent state: survives app crash/kill. Written atomically so a")
            appendLine("# reader never sees a half-written file. Read back by the app via the")
            appendLine("# state-resync script whenever the setup screen opens.")
            appendLine("write_state() {")
            appendLine("    printf 'status=%s\\nstage=%s\\npercent=%s\\nmessage=%s\\nts=%s\\n' \\")
            appendLine("        \"\$1\" \"\$2\" \"\$3\" \"\$4\" \"\$(date +%s)\" > \"\$STATE_FILE.tmp\" 2>/dev/null \\")
            appendLine("        && mv \"\$STATE_FILE.tmp\" \"\$STATE_FILE\" 2>/dev/null || true")
            appendLine("}")
            appendLine()
            appendLine("report_progress() {")
            appendLine("    local stage=\"\$1\" message=\"\$2\" percent=\"\$3\"")
            appendLine("    write_state running \"\$stage\" \"\$percent\" \"\$message\"")
            appendLine("    am broadcast -p \"\$RECEIVER\" -a \"\$PROGRESS_ACTION\" \\")
            appendLine("        --es stage \"\$stage\" \\")
            appendLine("        --es message \"\$message\" \\")
            appendLine("        --ei percent \"\$percent\" >/dev/null 2>&1 || true")
            appendLine("}")
            appendLine()
            appendLine("report_complete() {")
            appendLine("    write_state done complete 100 \"Installation complete\"")
            appendLine("    rm -f \"\$DONE_FILE\"")
            appendLine("    am broadcast -p \"\$RECEIVER\" -a \"\$COMPLETE_ACTION\" >/dev/null 2>&1 || true")
            appendLine("}")
            appendLine()
            appendLine("report_error() {")
            appendLine("    local message=\"\$1\"")
            appendLine("    write_state failed \"\${STAGE:-unknown}\" \"\${PERCENT:-0}\" \"\$message\"")
            appendLine("    am broadcast -p \"\$RECEIVER\" -a \"\$ERROR_ACTION\" --es message \"\$message\" >/dev/null 2>&1 || true")
            appendLine("}")
            appendLine()
            appendLine("# Single-instance lock: a second Install tap while one is running only")
            appendLine("# re-announces progress instead of corrupting the live install.")
            appendLine("if [ -f \"\$LOCK_FILE\" ] && kill -0 \"\$(cat \"\$LOCK_FILE\" 2>/dev/null)\" 2>/dev/null; then")
            appendLine("    report_progress \"already_running\" \"An install is already running — attaching to its progress.\" 1")
            appendLine("    exit 0")
            appendLine("fi")
            appendLine("echo \$\$ > \"\$LOCK_FILE\"")
            appendLine()
            appendLine("# Keep the CPU awake during the long Rust/Python builds. Without this,")
            appendLine("# Android may freeze Termux when the screen turns off, breaking the")
            appendLine("# install halfway. termux-api may not be installed — best effort.")
            appendLine("command -v termux-wake-lock >/dev/null 2>&1 && termux-wake-lock || true")
            appendLine()
            appendLine("cleanup() {")
            appendLine("    command -v termux-wake-unlock >/dev/null 2>&1 && termux-wake-unlock || true")
            appendLine("    rm -f \"\$LOCK_FILE\"")
            appendLine("    # Detect an interrupted install (Termux killed, phone rebooted...):")
            appendLine("    # if we exit while the state still says running, mark it failed so")
            appendLine("    # the app can offer Resume instead of showing a frozen progress bar.")
            appendLine("    if grep -q '^status=running' \"\$STATE_FILE\" 2>/dev/null; then")
            appendLine("        write_state failed \"\${STAGE:-unknown}\" \"\${PERCENT:-0}\" \"Install interrupted at stage \${STAGE:-unknown}. Tap Install again to resume — completed stages are skipped.\"")
            appendLine("    fi")
            appendLine("}")
            appendLine("trap cleanup EXIT")
            appendLine("trap 'report_error \"Install failed at stage: \$STAGE — tap Install again to resume from this stage. Log: ~/.hermes/logs/install.log\"' ERR")
            appendLine()
            appendLine("# Wait up to ~2 minutes for connectivity before declaring a network")
            appendLine("# failure — mobile networks drop and recover all the time.")
            appendLine("wait_for_network() {")
            appendLine("    local i=1")
            appendLine("    while [ \$i -le 12 ]; do")
            appendLine("        curl -fsI --max-time 8 \"https://hermes-agent.nousresearch.com\" >/dev/null 2>&1 && return 0")
            appendLine("        report_progress \"\${STAGE:-network}\" \"Waiting for network (\$i/12)...\" \"\${PERCENT:-5}\"")
            appendLine("        sleep 10")
            appendLine("        i=\$((i + 1))")
            appendLine("    done")
            appendLine("    return 1")
            appendLine("}")
            appendLine()
            appendLine("# Resume support: stages already completed by a previous (interrupted)")
            appendLine("# run are recorded and skipped, so a resume costs seconds, not minutes.")
            appendLine("stage_done() { [ -f \"\$DONE_FILE\" ] && grep -qx \"\$1\" \"\$DONE_FILE\" 2>/dev/null; }")
            appendLine("mark_stage_done() { echo \"\$1\" >> \"\$DONE_FILE\"; }")
            appendLine()
            appendLine("# Download install.sh")
            appendLine("STAGE=\"repository\"")
            appendLine("PERCENT=5")
            appendLine("report_progress \"\$STAGE\" \"Downloading Hermes Agent installer...\" 5")
            appendLine("# Bootstrap only what is needed to download the official installer.")
            appendLine("# Full prerequisites are installed by install.sh's prerequisites stage.")
            appendLine("if ! command -v curl >/dev/null 2>&1; then")
            appendLine("    pkg update -y 2>&1 | tee -a \"\$HOME/.hermes/logs/install.log\" || true")
            appendLine("    pkg install -y curl ca-certificates 2>&1 | tee -a \"\$HOME/.hermes/logs/install.log\"")
            appendLine("fi")
            appendLine("# Recover from failed installs that left a non-git repo path behind")
            appendLine("if [ -e \"\$REPO_DIR\" ] && [ ! -d \"\$REPO_DIR/.git\" ]; then")
            appendLine("    BROKEN_REPO_DIR=\"\$REPO_DIR.broken-\$(date +%Y%m%d-%H%M%S)\"")
            appendLine("    report_progress \"repository\" \"Moving non-git Hermes repo aside: \$BROKEN_REPO_DIR\" 6")
            appendLine("    echo \"Moving non-git Hermes repo aside: \$REPO_DIR -> \$BROKEN_REPO_DIR\" | tee -a \"\$HOME/.hermes/logs/install.log\"")
            appendLine("    mv \"\$REPO_DIR\" \"\$BROKEN_REPO_DIR\"")
            appendLine("fi")
            appendLine("DL_ATTEMPT=1")
            appendLine("while ! curl -fsSL \"\$INSTALL_URL\" -o \"\$HOME/hermes_install.sh\" 2>>\"\$HOME/.hermes/logs/install.log\"; do")
            appendLine("    if [ \$DL_ATTEMPT -ge 3 ]; then")
            appendLine("        report_error \"Could not download the installer after 3 attempts. Check your internet connection and tap Install again.\"")
            appendLine("        exit 1")
            appendLine("    fi")
            appendLine("    DL_ATTEMPT=\$((DL_ATTEMPT + 1))")
            appendLine("    report_progress \"\$STAGE\" \"Download failed — retrying (\$DL_ATTEMPT/3)...\" 5")
            appendLine("    wait_for_network || true")
            appendLine("done")
            appendLine("chmod +x \"\$HOME/hermes_install.sh\"")
            appendLine()
            appendLine("prepare_android_rust_env() {")
            appendLine("    if [ -z \"\${ANDROID_API_LEVEL:-}\" ]; then")
            appendLine("        ANDROID_API_LEVEL=\$(getprop ro.build.version.sdk 2>/dev/null || true)")
            appendLine("        [ -n \"\$ANDROID_API_LEVEL\" ] || ANDROID_API_LEVEL=24")
            appendLine("        export ANDROID_API_LEVEL")
            appendLine("    fi")
            appendLine("    # maturin/jiter builds on Termux often need the native Rust target")
            appendLine("    # spelled out explicitly, otherwise build isolation can fail while")
            appendLine("    # installing jiter's Rust build dependencies.")
            appendLine("    if command -v rustc >/dev/null 2>&1; then")
            appendLine("        CARGO_BUILD_TARGET=\$(rustc -Vv | awk '/^host:/ {print \$2; exit}')")
            appendLine("        [ -n \"\$CARGO_BUILD_TARGET\" ] && export CARGO_BUILD_TARGET")
            appendLine("    fi")
            appendLine("    # Do not inherit a user's ~/.cargo/config mirror override. Broken")
            appendLine("    # replace-with mirrors (e.g. USTC returning 404) make maturin fail")
            appendLine("    # before jiter can build. Use a Hermes-scoped clean Cargo home.")
            appendLine("    export CARGO_HOME=\"\$HOME/.hermes/cargo\"")
            appendLine("    mkdir -p \"\$CARGO_HOME\"")
            appendLine("    export CARGO_REGISTRIES_CRATES_IO_PROTOCOL=sparse")
            appendLine("    # Termux rustc 1.96 currently ICEs while building pydantic-core")
            appendLine("    # with linker-plugin-lto/codegen-units=1. Override Cargo's release")
            appendLine("    # profile to a safer no-LTO build for Android native wheels.")
            appendLine("    export CARGO_PROFILE_RELEASE_LTO=false")
            appendLine("    export CARGO_PROFILE_RELEASE_CODEGEN_UNITS=16")
            appendLine("    export CARGO_PROFILE_RELEASE_STRIP=none")
            appendLine("    export CARGO_BUILD_JOBS=1")
            appendLine("}")
            appendLine()
            appendLine("ensure_termux_rust_build_prereqs() {")
            appendLine("    # Match the tested manual Termux bootstrap: upgrade stale packages")
            appendLine("    # first, then install the compiler/linker stack needed by jiter/maturin.")
            appendLine("    pkg upgrade -y 2>&1 | tee -a \"\$HOME/.hermes/logs/install.log\" || true")
            appendLine("    pkg install -y python clang rust make pkg-config libffi openssl ca-certificates curl llvm lld 2>&1 | tee -a \"\$HOME/.hermes/logs/install.log\" || true")
            appendLine("    prepare_android_rust_env")
            appendLine("}")
            appendLine()
            appendLine("prepare_android_rust_env")
            appendLine()
            appendLine("# Get stage manifest (Fix S2F02: use --manifest)")
            appendLine("MANIFEST=\$(bash \"\$HOME/hermes_install.sh\" --manifest 2>/dev/null || true)")
            appendLine("if [ -z \"\$MANIFEST\" ]; then")
            appendLine("    # Fallback: run install.sh directly if manifest fails. Keep this")
            appendLine("    # non-interactive so the Android app never blocks on a shell prompt.")
            appendLine("    STAGE=\"prerequisites\"")
            appendLine("    PERCENT=10")
            appendLine("    report_progress \"\$STAGE\" \"Running install.sh...\" 10")
            appendLine("    bash \"\$HOME/hermes_install.sh\" --skip-setup 2>&1 | tee -a \"\$HOME/.hermes/logs/install.log\"")
            appendLine("else")
            appendLine("    # Parse the manifest instead of hard-coding stages. Upstream owns the")
            appendLine("    # stage list; this app only drives the documented protocol.")
            appendLine("    STAGES=\$(printf '%s' \"\$MANIFEST\" | python3 -c \"import sys,json; print('\\n'.join(s['name'] for s in json.loads(sys.stdin.read())['stages']))\" 2>/dev/null || true)")
            appendLine("    if [ -z \"\$STAGES\" ]; then")
            appendLine("        STAGES=\$(printf '%s\\n' prerequisites repository venv python-deps node-deps path config setup gateway complete)")
            appendLine("    fi")
            appendLine("    STAGE_COUNT=\$(printf '%s\\n' \"\$STAGES\" | sed '/^$/d' | wc -l | tr -d ' ')")
            appendLine("    if [ -z \"\$STAGE_COUNT\" ] || [ \"\$STAGE_COUNT\" -le 0 ]; then STAGE_COUNT=10; fi")
            appendLine("    CURRENT=0")
            appendLine("    while IFS= read -r STAGE; do")
            appendLine("        [ -z \"\$STAGE\" ] && continue")
            appendLine("        CURRENT=\$((CURRENT + 1))")
            appendLine("        PERCENT=\$((CURRENT * 88 / STAGE_COUNT))")
            appendLine("        # Resume: skip stages a previous interrupted run already finished.")
            appendLine("        if stage_done \"\$STAGE\"; then")
            appendLine("            report_progress \"\$STAGE\" \"Stage \$STAGE already done — skipping (resume)\" \$PERCENT")
            appendLine("            continue")
            appendLine("        fi")
            appendLine("        report_progress \"\$STAGE\" \"Running stage: \$STAGE\" \$PERCENT")
            appendLine("        if [ \"\$STAGE\" = \"python-deps\" ]; then")
            appendLine("            ensure_termux_rust_build_prereqs")
            appendLine("        fi")
            appendLine("        # Run stage with --json output (Fix S2F02). --non-interactive lets")
            appendLine("        # upstream skip setup/gateway prompt stages cleanly. Each stage gets")
            appendLine("        # 3 attempts with a network-wait between them, so one dropped")
            appendLine("        # connection doesn't kill a 15-minute install.")
            appendLine("        ATTEMPT=1")
            appendLine("        STAGE_OK=0")
            appendLine("        while [ \$ATTEMPT -le 3 ]; do")
            appendLine("            if STAGE_RESULT=\$(bash \"\$HOME/hermes_install.sh\" --stage \"\$STAGE\" --json --non-interactive 2>&1 | tee -a \"\$HOME/.hermes/logs/install.log\"); then")
            appendLine("                STAGE_OK=1")
            appendLine("                break")
            appendLine("            fi")
            appendLine("            # Known auto-fix: psutil needs the Android shim inside the venv.")
            appendLine("            if [ \"\$STAGE\" = \"python-deps\" ] && printf '%s\\n' \"\$STAGE_RESULT\" | grep -qi \"platform android is not supported\"; then")
            appendLine("                report_progress \"\$STAGE\" \"Applying psutil Android shim fix...\" \$PERCENT")
            appendLine("                PIP_PYTHON=\"\$REPO_DIR/venv/bin/python\"")
            appendLine("                [ -x \"\$PIP_PYTHON\" ] || PIP_PYTHON=\"\$(command -v python3)\"")
            appendLine("                if [ -f \"\$REPO_DIR/scripts/install_psutil_android.py\" ]; then")
            appendLine("                    \"\$PIP_PYTHON\" \"\$REPO_DIR/scripts/install_psutil_android.py\" --pip \"\$PIP_PYTHON -m pip\" 2>&1 | tee -a \"\$HOME/.hermes/logs/install.log\" || true")
            appendLine("                fi")
            appendLine("            fi")
            appendLine("            ATTEMPT=\$((ATTEMPT + 1))")
            appendLine("            if [ \$ATTEMPT -le 3 ]; then")
            appendLine("                report_progress \"\$STAGE\" \"Stage \$STAGE failed — retrying (attempt \$ATTEMPT/3)...\" \$PERCENT")
            appendLine("                wait_for_network || true")
            appendLine("                sleep 5")
            appendLine("            fi")
            appendLine("        done")
            appendLine("        if [ \$STAGE_OK -eq 1 ]; then")
            appendLine("            mark_stage_done \"\$STAGE\"")
            appendLine("            continue")
            appendLine("        fi")
            appendLine("        if [ \"\$STAGE\" = \"complete\" ] && command -v hermes >/dev/null 2>&1; then")
            appendLine("            report_progress \"\$STAGE\" \"Hermes installed successfully (ignoring complete stage warning)\" \$PERCENT")
            appendLine("            mark_stage_done \"\$STAGE\"")
            appendLine("            continue")
            appendLine("        fi")
            appendLine("        report_error \"Stage \$STAGE failed after 3 attempts: \$STAGE_RESULT — tap Install again to resume from this stage.\"")
            appendLine("        exit 1")
            appendLine("    done <<EOF")
            appendLine("\$STAGES")
            appendLine("EOF")
            appendLine("fi")
            appendLine()
            appendLine("# The Android app talks to `hermes dashboard` /api/ws. If upstream fell")
            appendLine("# back from .[termux-all] to .[termux], make sure the web extra exists.")
            appendLine("STAGE=\"dashboard_deps\"")
            appendLine("PERCENT=90")
            appendLine("report_progress \"\$STAGE\" \"Checking dashboard WebSocket dependencies...\" 90")
            appendLine("DASHBOARD_PY=\"\$REPO_DIR/venv/bin/python\"")
            appendLine("[ -x \"\$DASHBOARD_PY\" ] || DASHBOARD_PY=\"\$(command -v python3)\"")
            appendLine("if [ -d \"\$REPO_DIR\" ] && ! \"\$DASHBOARD_PY\" -c \"import fastapi, uvicorn, starlette\" >/dev/null 2>&1; then")
            appendLine("    report_progress \"\$STAGE\" \"Installing Hermes dashboard web extra...\" 90")
            appendLine("    (cd \"\$REPO_DIR\" && \"\$DASHBOARD_PY\" -m pip install -e '.[web]' -c constraints-termux.txt) 2>&1 | tee -a \"\$HOME/.hermes/logs/install.log\"")
            appendLine("fi")
            appendLine()
            appendLine("# Verify: hermes --version (Fix S2F05)")
            appendLine("STAGE=\"verify_version\"")
            appendLine("PERCENT=92")
            appendLine("report_progress \"\$STAGE\" \"Checking hermes --version...\" 92")
            appendLine("export PATH=/data/data/com.termux/files/usr/bin:\$HOME/.hermes/hermes-agent/venv/bin:\$HOME/.hermes/venv/bin:\$HOME/.venv/bin:\$HOME/.local/bin:\$PATH")
            appendLine("HERMES_CMD=\"/data/data/com.termux/files/usr/bin/hermes\"")
            appendLine("if [ -f \"\$HOME/.hermes/hermes-agent/venv/bin/hermes\" ]; then")
            appendLine("    HERMES_CMD=\"\$HOME/.hermes/hermes-agent/venv/bin/hermes\"")
            appendLine("elif [ -f \"\$HOME/.hermes/venv/bin/hermes\" ]; then")
            appendLine("    HERMES_CMD=\"\$HOME/.hermes/venv/bin/hermes\"")
            appendLine("elif [ -f \"\$HOME/.venv/bin/hermes\" ]; then")
            appendLine("    HERMES_CMD=\"\$HOME/.venv/bin/hermes\"")
            appendLine("elif [ -f \"\$HOME/.local/bin/hermes\" ]; then")
            appendLine("    HERMES_CMD=\"\$HOME/.local/bin/hermes\"")
            appendLine("elif ! [ -f \"\$HERMES_CMD\" ] && command -v hermes >/dev/null 2>&1; then")
            appendLine("    HERMES_CMD=\"\$(command -v hermes)\"")
            appendLine("fi")
            appendLine("if ! [ -x \"\$HERMES_CMD\" ]; then")
            appendLine("    report_error \"Hermes command not found after install. Expected \$HERMES_CMD. Check \$HOME/.hermes/logs/install.log\"")
            appendLine("    exit 1")
            appendLine("fi")
            appendLine("HERMES_VERSION=\$(\"\$HERMES_CMD\" --version 2>&1)")
            appendLine("am broadcast -p \"\$RECEIVER\" -a \"\$PROGRESS_ACTION\" \\")
            appendLine("    --es stage \"verify_version\" \\")
            appendLine("    --es message \"Hermes version: \$HERMES_VERSION\" \\")
            appendLine("    --ei percent 94 >/dev/null 2>&1 || true")
            appendLine()
            appendLine("# Verify: hermes doctor (Fix S2F06)")
            appendLine("STAGE=\"verify_doctor\"")
            appendLine("PERCENT=96")
            appendLine("report_progress \"\$STAGE\" \"Running hermes doctor...\" 96")
            appendLine("DOCTOR_OUTPUT=\$(\"\$HERMES_CMD\" doctor 2>&1 || echo \"doctor ready\")")
            appendLine("am broadcast -p \"\$RECEIVER\" -a \"\$PROGRESS_ACTION\" \\")
            appendLine("    --es stage \"verify_doctor\" \\")
            appendLine("    --es message \"Doctor: \$DOCTOR_OUTPUT\" \\")
            appendLine("    --ei percent 98 >/dev/null 2>&1 || true")
            appendLine()
            appendLine("# Detect Python version (Fix S2F01)")
            appendLine("PYTHON_VERSION=\$(python3 --version 2>&1 || echo \"unknown\")")
            appendLine("am broadcast -p \"\$RECEIVER\" -a \"\$PROGRESS_ACTION\" \\")
            appendLine("    --es stage \"python_version\" \\")
            appendLine("    --es message \"Python: \$PYTHON_VERSION\" \\")
            appendLine("    --ei percent 99 >/dev/null 2>&1 || true")
            appendLine()
            appendLine("STAGE=\"complete\"")
            appendLine("PERCENT=100")
            appendLine("report_progress \"\$STAGE\" \"Installation complete! Hermes: \$HERMES_VERSION, Python: \$PYTHON_VERSION\" 100")
            appendLine("report_complete")
        }
    }

    /**
     * Small script that re-broadcasts the persisted install state to the app.
     *
     * Fired when the setup screen opens (see TermuxBridge.detect). If the app
     * crashed or was closed mid-install, this restores the UI from
     * `~/.hermes/install.state` using the SAME broadcast actions the live
     * installer uses — no extra receiver logic needed. It also detects a
     * silently-dead installer (state says running but the PID is gone) and
     * converts it to a resumable error.
     */
    fun generateStateResyncScript(): String {
        val receiver = context.packageName
        return buildString {
            appendLine("STATE_FILE=\"\$HOME/.hermes/install.state\"")
            appendLine("LOCK_FILE=\"\$HOME/.hermes/.install.pid\"")
            appendLine("[ -f \"\$STATE_FILE\" ] || exit 0")
            appendLine("status=\$(sed -n 's/^status=//p' \"\$STATE_FILE\" | head -1)")
            appendLine("stage=\$(sed -n 's/^stage=//p' \"\$STATE_FILE\" | head -1)")
            appendLine("percent=\$(sed -n 's/^percent=//p' \"\$STATE_FILE\" | head -1)")
            appendLine("message=\$(sed -n 's/^message=//p' \"\$STATE_FILE\" | head -1)")
            appendLine("case \"\$status\" in")
            appendLine("  done)")
            appendLine("    am broadcast -p \"$receiver\" -a \"${BroadcastAction.COMPLETE.action}\" >/dev/null 2>&1 || true ;;")
            appendLine("  failed)")
            appendLine("    am broadcast -p \"$receiver\" -a \"${BroadcastAction.ERROR.action}\" --es message \"\$message\" >/dev/null 2>&1 || true ;;")
            appendLine("  running)")
            appendLine("    if [ -f \"\$LOCK_FILE\" ] && kill -0 \"\$(cat \"\$LOCK_FILE\" 2>/dev/null)\" 2>/dev/null; then")
            appendLine("        am broadcast -p \"$receiver\" -a \"${BroadcastAction.PROGRESS.action}\" \\")
            appendLine("            --es stage \"\$stage\" --es message \"\$message\" --ei percent \"\${percent:-0}\" >/dev/null 2>&1 || true")
            appendLine("    else")
            appendLine("        printf 'status=failed\\nstage=%s\\npercent=%s\\nmessage=%s\\nts=%s\\n' \"\$stage\" \"\${percent:-0}\" \"Install was interrupted at stage \$stage. Tap Install to resume.\" \"\$(date +%s)\" > \"\$STATE_FILE\" 2>/dev/null || true")
            appendLine("        am broadcast -p \"$receiver\" -a \"${BroadcastAction.ERROR.action}\" \\")
            appendLine("            --es message \"Install was interrupted at stage \$stage. Tap Install to resume — completed stages are skipped.\" >/dev/null 2>&1 || true")
            appendLine("    fi ;;")
            appendLine("esac")
        }
    }

    /**
     * Legacy entry point preserved for the fallback "copy/paste" instructions
     * screen. The automated path uses [generateInstallScript] instead.
     */
    fun generateInstallCommand(): String = generateInstallScript()

    fun getScriptFilePath(): java.io.File? = null
}
